### ISSUE TITLE
dependent parameters

### ISSUE THREAD

**Issue by NicolasRouquette** [vigoo/clipp#175]
Suppose I want to define an application that takes parameters like this:

```
app --dir /data --in ./src/input --out ./out/result
```

where the meaning of `-in` and `-out` are file paths that are relative to `--dir`.

I would like to define the parameters `--in` and `--out` dependent on the parameter `--dir` so that I could have access to the value of the `--dir` parameter in the custom parsers for `--in` and `--out`.

In this example, the custom parser for `--in` would verify that the relative path, `./src/input`, exists in the directory specified by `--dir`, ie., `/data/src/input`.

**Comment by vigoo** [comment]
What this would really mean I think is the ability to lift an arbitrary effect to the parser monad, so you can write the existence check and use the `fail` I've just added to express this. The interesting question here is what would happen to the usage info generator. 

Note that you can produce the combined directories right now, just without checking the file's existence, with something like
```scala
for {
  data <- namedParam()
  relIn <- namedParam()
  relOut <- namedParam()
} yield (data / relIn, data / relOut)
```

One solution of course would be to not solve this and defer the extra validation to outside of the parameter parsing, but I understand that would create more boilerplate.

Another possibility would be to provide two functions when lifting the effect, the real one and a pure simulation that can be called in the usage graph builder.

It would look something like:

```scala
case class Path(s)
case class ValidatedPath(path: Path)

def validate(path: Path): Task[ValidatedPath]

for {
  root <- namedParam[Path]()
  child <- namedParam[Path]()
  full = root / child
  validatedFull <- lift(validate, ValidatedPath(_))
} yield validatedFull
```

which means that during parsing we run the effect `validate` but for usage graph building we always assume the paths are validated.

What do you think?

**Comment by NicolasRouquette** [comment]
Thanks for the feedback, I really like the `validate` approach, it seems to be more general than the use case in this issue. For example, one could use this mechanism to ensure that a combination of options is acceptable. 

For example, imagine that an application could be invoked with any 2 of 3 options: `-a`, `-b`, `-c`.
So, `-a -b`, `-a -c`, `-b -c` would be OK but `-a -b -c` would not.
I believe that this use case could also be handled with your `validate` idea.
