### ISSUE TITLE
parsing parameters with multiple values

### ISSUE THREAD

**Issue by NicolasRouquette** [vigoo/clipp#177]
I would like to define a parameters class like this;

```
case class Parameters(x: List[String], y: String)
```

and use clipp to parse the command line arguments like this:

```
app -x v1 v2 v3 -y foo
```

or like this:

```
app -x v1 -x v2 -x v3 -y foo
```

**Comment by vigoo** [comment]
I think the second example is easy to implement. I would probably not do the first, it does not mix well with non-named parameters.

Also note that you can always create a list parser that accepts `app -x "v1, v2, v3" -y foo` (actually I think that should be added to the library too)

**Comment by vigoo** [comment]
- #183 implements parser for iterables, so you can handle `app -x "v1, v2, v3"
- #184 adds a new modifier `repeated { ... }` which can handle `app -x v1 -x v2 -x v3`

**Comment by NicolasRouquette** [comment]
Thanks, this is awesome!

**Comment by NicolasRouquette** [comment]
Could you please make a new release with these fixes?
