### ISSUE TITLE
ZIO 2 release

### ISSUE THREAD

**Issue by kubukoz** [vigoo/clipp#339]
Hi! I see that zio 2 support is on master. Can you make a release please?

**Comment by vigoo** [comment]
It should be released for final ZIO 2.0.0: https://search.maven.org/artifact/io.github.vigoo/clipp-zio-2_2.13/0.6.8/jar 

but of course I can do a new one if needed

**Comment by vigoo** [comment]
Note that there are both zio and zio-2 versions published for now, I'll drop the ZIO 1 one now that ZIO 2 is final

**Comment by kubukoz** [comment]
ah, I see - missed the new artifact. Thanks :)
